##mysql
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "3308"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}

---
##Make sure to deploy mysql service first
##/mysql --> mysql-service.yml
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-expose
  namespace: default
  selfLink: 
  uid: 
  resourceVersion: 
  creationTimestamp: 
  labels:
    io.kompose.service: phpmyadmin
spec:
  ports:
    - name: myadmin
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin
  clusterIP: 
  type: NodePort
  sessionAffinity: None 
status:
loadBalancer:  
   
---
#Ingress  
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: possi70.kube
    http:
      paths:
        - path: /
          backend:
            serviceName: php70-expose
            servicePort: ph70 