version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    # restart: unless-stopped
    environment:
      - VIRTUAL_HOST=variable.local
    #     # - VIRTUAL_PORT=80
    expose:
      - "5000"
    # env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    # ports:
    #     - "3006:3006"
    #     - "5000:5000"
    volumes:
      - ./variable/:/home/node/app:z
      - /home/node/app/node_modules
      - /home/node/app/client/node_modules
    network_mode: ngix_default
    command: /home/node/app/node_modules/.bin/nodemon server.js
    #command: npm run dev

  client:
    image: nodejs
    container_name: devreact
    expose:
      - "3006"
    ports:
      - "3006:3006"
    volumes:
      - ./variable/client:/home/node/app/client:z
      - /home/node/app/client/node_modules
    network_mode: ngix_default
    command: npm run client

  # mongodb:
  #   image: mongo:4.1.8-xenial
  #   container_name: mongodb
  #   # restart: unless-stopped
  #   # env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME= tusharU
  #     - MONGO_INITDB_ROOT_PASSWORD= tusharUpdate
  #   ports:
  #   - "27017:27017"
  #   volumes:
  #     - /usr/local/var/mongodb:/data/db
  #   network_mode: ngix_default
# networks:
#   app-network:
#     driver: bridge

# volumes:
#   dbdata:
#   node_modules:
