version: "3.2"
services:
  php:
    # build: 
    #   context: .
    image: possimg
    # networks:
    #   - frontend
    #   - backend
    environment:
      - VIRTUAL_HOST=possi70.local
      - VIRTUAL_PORT=80
      - MYSQL_HOST=mysql-app
    # environment:
    #   - MYSQL_HOST=moe-mysql-app
    #   - MYSQL_USER=moeuser
    #   - MYSQL_PASSWORD=moepass
    #   - MYSQL_DB=moe_db
    volumes:
      - ../www/:/var/www/html:z
    # extra_hosts: 
    #     - "possi72.local:127.0.0.1"
    # hostname:  possi72.local
    # domainname: local     
    ports:
      - "8090:80"
    container_name: possi70
    network_mode: ngix_default
