version: "3.2"
services:
  php:
    build: 
       context: .
    image: doorstep
    # networks:
    #   - frontend
    #   - backend
    environment:
      - VIRTUAL_HOST=doorstep.test
      - VIRTUAL_PORT=80
      - MYSQL_HOST=mysql-app
    # environment:
    #   - MYSQL_HOST=moe-mysql-app
    #   - MYSQL_USER=moeuser
    #   - MYSQL_PASSWORD=moepass
    #   - MYSQL_DB=moe_db
    volumes:
      - ../../../doorstep:/var/www/html:z
     
    ports:
      - "9090:80"
    container_name: doorstep
    network_mode: ngix_default
