version: "3.2"
services:
  php:
    build: 
      context: .
    image: possi72
    # networks:
    #   - frontend
    #   - backend
    environment:
      - VIRTUAL_HOST=possi72.local
      - VIRTUAL_PORT=80
    # environment:
    #   - MYSQL_HOST=moe-mysql-app
    #   - MYSQL_USER=moeuser
    #   - MYSQL_PASSWORD=moepass
    #   - MYSQL_DB=moe_db
    volumes:
      - ../../www/:/var/www/html:z
    # extra_hosts: 
    #     - "possi72.local:127.0.0.1"
    # hostname:  possi72.local
    # domainname: local     
    ports:
      - "9090:80"
    container_name: possiupgrade
    network_mode: ngix_default
  # mysql:
  #   image: mysql:5.7
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_USER=moeuser
  #     - MYSQL_PASSWORD=moepass 
  #     - MYSQL_DATABASE=moe_db
  #   container_name: moe-mysql-app
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.7
  #   depends_on:
  #     - mysql
  #   networks:
  #     - backend
  #   ports:
  #     - "30002:80"
  #   environment:
  #     - PMA_HOST=moe-mysql-app
  #     - PMA_PORT= 3306
  #   volumes:
  #     - /sessions
  #   container_name: moe-phpmyadmin-app
# networks:
#   frontend:
#   backend: